### ISSUE TITLE
Crash when Sneak Wrench Catwalk Railings

### ISSUE THREAD

**Issue by marshall-1977** [talrey/CreateDeco#118] opened 2024-01-24 07:07 UTC
When using the Wrench to disassemble/remove the Catwalk Railing, Minecraft/Create Deco throws an NoClassDefFound Error

**Using:** createdeco-2.0.0-fabric-1.20.1 version.

**How to replicate:** Place a catwalk railing bock. Then use the wrench and sneak-click it to remove it.

**Exception from crash log below:**

java.lang.NoClassDefFoundError: net/minecraft/class_638
	at com.github.talrey.createdeco.blocks.CatwalkRailingBlock.onSneakWrenched(CatwalkRailingBlock.java:77)
	at com.simibubi.create.content.equipment.wrench.WrenchItem.method_7884(WrenchItem.java:55)
	at net.minecraft.class_1799.method_7981(class_1799.java:272)
	at net.minecraft.class_3225.method_14262(class_3225.java:363)
	at net.minecraft.class_3244.method_12046(class_3244.java:1140)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 21 more

**Comment by kurisubrooks** [comment] 2024-01-27 07:09
+1 also experiencing this - had to disable catwalks for now as it takes down our server every time

**Comment by drewcassidy** [comment] 2024-02-06 20:01
Looks like a duplicate of #108

**Comment by e-g-t** [comment] 2024-02-13 05:37
I just experienced this issue. I can provide more logs if needed. 
I hope all the items gain the ability to be broken with the wrench, including the lamps!

**Comment by Atyneton** [comment] 2024-02-18 21:49
Can confirm this bug still happens, crashed the "All Of Fabric" server by accident because I thought this got fixed a while back, apparently not.

**Comment by hatkidchan** [comment] 2024-03-23 10:14
Same happens to me on Create Deco 2.0.1

**Comment by vitecekuwu** [comment] 2024-04-01 13:56
getting a similar error when wrench-clicking a catwalk stair w/ railing too, fabric 1.20.1 ver. 2.0.1 -> nolog.link/s/createdeco-crash

**Comment by AstralOrdana** [comment] 2024-04-26 19:22
fixed for 2.0.2

**Closed as completed by AstralOrdana** 2024-04-26 19:22 UTC
