### ISSUE TITLE
Error with createdeco-fabric-1.2.7-1.18.2.jar on fabric

### ISSUE THREAD

**Issue by pavog** [talrey/CreateDeco#23] opened 2022-05-30 09:41 UTC
Hi there I use fabric server 1.18.2 (0.14.6) with [createdeco-fabric-1.2.7-1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/create-deco/files/3795326).

I get the following error on startup:

```
[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createdeco'!
```

Full log:
https://mclo.gs/jWa6z30

**Comment by itsdinkd** [comment] 2022-05-31 09:49
Create Deco latest fabric update (released 12 hours ago) still breaks servers.

**Comment by ghost** [comment] 2022-06-21 22:30
Duplicate of #12

**Closed as completed** 2022-09-26 04:50 UTC
